FROM apline:3.1

#Update
RUN apk add --Update python py-pip

#Install app dependencies
RUN pip install -r requirements.txt

COPY simpleapp.py /src/simpleapp.py

EXPOSE 8000
CMD ["python", "/src/simpleapp.py", "-p 8000"]